#pragma once

#include "artistview.hpp"
#include "audiofeaturesview.hpp"
#include "darkpalette.hpp"
#include "icon.hpp"
#include "lyricsview.hpp"
#include "mainmenu.hpp"
#include "mediaplayer/service.hpp"
#include "playlistmenu.hpp"
#include "searchview.hpp"
#include "settingsdialog.hpp"
#include "songmenu.hpp"
#include "spotify/audiofeatures.hpp"
#include "spotify/clienthandler.hpp"
#include "spotify/playback.hpp"
#include "spotify/playlist.hpp"
#include "spotify/spotify.hpp"
#include "spotify/user.hpp"
#include "spotify/webplayer.hpp"
#include "trayicon.hpp"
#include "utils.hpp"
#include "volumebutton.hpp"
#include "whatsnewdialog.hpp"

#include <QAction>
#include <QApplication>
#include <QClipboard>
#include <QCloseEvent>
#include <QDockWidget>
#include <QFileInfo>
#include <QGroupBox>
#include <QHBoxLayout>
#include <QHeaderView>
#include <QIcon>
#include <QLabel>
#include <QListWidget>
#include <QListWidget>
#include <QMainWindow>
#include <QMapIterator>
#include <QMenu>
#include <QMessageBox>
#include <QPainter>
#include <QPainterPath>
#include <QSlider>
#include <QSplitter>
#include <QStatusBar>
#include <QTextEdit>
#include <QToolBar>
#include <QToolButton>
#include <QTreeWidget>
#include <QVBoxLayout>