#pragma once

#include "artistview.hpp"
#include "audiofeaturesview.hpp"
#include "dialog/settingsdialog.hpp"
#include "dialog/splashdialog.hpp"
#include "dialog/whatsnewdialog.hpp"
#include "list/librarylist.hpp"
#include "list/playlistlist.hpp"
#include "list/trackslist.hpp"
#include "lyricsview.hpp"
#include "maintoolbar.hpp"
#include "mediaplayer/service.hpp"
#include "menu/mainmenu.hpp"
#include "menu/playlistmenu.hpp"
#include "menu/songmenu.hpp"
#include "searchview.hpp"
#include "spotify/audiofeatures.hpp"
#include "spotify/clienthandler.hpp"
#include "spotify/playback.hpp"
#include "spotify/playlist.hpp"
#include "spotify/spotify.hpp"
#include "spotify/user.hpp"
#include "spotify/webplayer.hpp"
#include "trayicon.hpp"
#include "util/darkpalette.hpp"
#include "util/icon.hpp"
#include "util/utils.hpp"
#include "volumebutton.hpp"

#include <QAction>
#include <QApplication>
#include <QClipboard>
#include <QCloseEvent>
#include <QDockWidget>
#include <QFileInfo>
#include <QGroupBox>
#include <QHBoxLayout>
#include <QHeaderView>
#include <QIcon>
#include <QLabel>
#include <QListWidget>
#include <QListWidget>
#include <QMainWindow>
#include <QMapIterator>
#include <QMenu>
#include <QMessageBox>
#include <QPainter>
#include <QPainterPath>
#include <QSlider>
#include <QSplitter>
#include <QStatusBar>
#include <QTextEdit>
#include <QToolBar>
#include <QToolButton>
#include <QTreeWidget>
#include <QVBoxLayout>