name: spotify-qt
summary: Lightweight Spotify client using Qt
description: A Spotify client using Qt as a simpler, lighter alternative to the official client, inspired by spotify-tui.
adopt-info: spotify-qt
license: GPL-3.0
grade: stable
confinement: strict
base: core24
icon: snap/gui/icon.png

parts:
  spotify-qt:
    plugin: cmake
    source: .
    build-packages:
      - git
      - g++
      - make
      - cmake
      - qt6-svg-dev
    stage-packages:
      - libqt6svg6
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0)
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
  cleanup:
    after:
      - spotify-qt
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
      - qt-common-themes
    override-prime: |
      # Remove duplicate files in the dependent snaps from the final snap.
      for snap in "core24" "kf6-core24" "qt-common-themes"; do
          cd "/snap/$snap/current" && find . -type f,l ! -xtype d -print | sed "s|^./|$CRAFT_PRIME|" | xargs rm -f
          cd "/snap/$snap/current" && find . -type f,l ! -xtype d -print | sed "s|^./|$CRAFT_PRIME/usr|" | xargs rm -f
      done

slots:
  dbus-mpris:
    interface: dbus
    bus: session
    name: org.mpris.MediaPlayer2.spotify-qt

apps:
  spotify-qt:
    command: usr/bin/spotify-qt
    extensions: [kde-neon-6]
    desktop: usr/share/applications/spotify-qt.desktop
    plugs:
      - home
      - gsettings
    slots: [dbus-mpris]
