on:
  push:
    branches: [stable]
  pull_request:
name: Flatpak
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: io.github.kraxarn.spotifyqt.flatpak
        manifest-path: io.github.kraxarn.spotifyqt.yml
        cache-key: flatpak-builder-${{ github.sha }}