name: Windows

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release
  CMAKE_GENERATOR: "Visual Studio 17 2022"

jobs:
  build:
    name: "${{matrix.name}}"
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        include:
          - name: "qt5-win32"
            os: windows-2022
            qt-version: "5.15.2"
            qt-arch: "win32_msvc2019"
            qt-host: "windows"
            cmake-arch: "Win32"
            use-qt5: "ON"

          - name: "qt6-win64"
            os: windows-2022
            qt-version: "6.10.2"
            qt-arch: "win64_msvc2022_64"
            qt-host: "windows"
            cmake-arch: "x64"
            use-qt5: "OFF"

          - name: "qt6-woa64"
            os: windows-11-arm
            qt-version: "6.10.2"
            qt-arch: "win64_msvc2022_arm64"
            qt-host: "windows_arm64"
            cmake-arch: "ARM64"
            use-qt5: "OFF"

    steps:
      - uses: actions/checkout@v6

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
          version: ${{matrix.qt-version}}
          arch: ${{matrix.qt-arch}}
          host: ${{matrix.qt-host}}

      - name: Configure CMake
        run: cmake . -G "${{env.CMAKE_GENERATOR}}" -A "${{matrix.cmake-arch}}" -D CMAKE_BUILD_TYPE="${{env.BUILD_TYPE}}" -D USE_TESTS=ON -D USE_LTO=ON -D USE_QT5="${{matrix.use-qt5}}"

      - name: Build
        run: cmake --build . --config ${{env.BUILD_TYPE}}

      - name: Test
        run: ${{runner.workspace}}\spotify-qt\lib\test\${{env.BUILD_TYPE}}\spotify-qt-lib-test.exe

      - name: Package
        run: windeployqt --no-opengl-sw ${{runner.workspace}}\spotify-qt\${{env.BUILD_TYPE}}\spotify-qt.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: spotify-qt-${{matrix.name}}
          path: ${{runner.workspace}}\spotify-qt\${{env.BUILD_TYPE}}
